# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clausia_pb2 as clausia__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clausia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClausIAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/clausia.ClausIA/Extract',
                request_serializer=clausia__pb2.ExtractRequest.SerializeToString,
                response_deserializer=clausia__pb2.ExtractResponse.FromString,
                _registered_method=True)
        self.ExtractMetadata = channel.unary_unary(
                '/clausia.ClausIA/ExtractMetadata',
                request_serializer=clausia__pb2.ExtractRequest.SerializeToString,
                response_deserializer=clausia__pb2.ExtractMetadataResponse.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_unary(
                '/clausia.ClausIA/Summarize',
                request_serializer=clausia__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=clausia__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.AnalyzeRisk = channel.unary_unary(
                '/clausia.ClausIA/AnalyzeRisk',
                request_serializer=clausia__pb2.ExtractRequest.SerializeToString,
                response_deserializer=clausia__pb2.AnalyzeRiskResponse.FromString,
                _registered_method=True)
        self.CheckCompliance = channel.unary_unary(
                '/clausia.ClausIA/CheckCompliance',
                request_serializer=clausia__pb2.ExtractRequest.SerializeToString,
                response_deserializer=clausia__pb2.CheckComplianceResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/clausia.ClausIA/Chat',
                request_serializer=clausia__pb2.ChatRequest.SerializeToString,
                response_deserializer=clausia__pb2.ChatResponse.FromString,
                _registered_method=True)


class ClausIAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Extract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCompliance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClausIAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=clausia__pb2.ExtractRequest.FromString,
                    response_serializer=clausia__pb2.ExtractResponse.SerializeToString,
            ),
            'ExtractMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractMetadata,
                    request_deserializer=clausia__pb2.ExtractRequest.FromString,
                    response_serializer=clausia__pb2.ExtractMetadataResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=clausia__pb2.SummarizeRequest.FromString,
                    response_serializer=clausia__pb2.SummarizeResponse.SerializeToString,
            ),
            'AnalyzeRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeRisk,
                    request_deserializer=clausia__pb2.ExtractRequest.FromString,
                    response_serializer=clausia__pb2.AnalyzeRiskResponse.SerializeToString,
            ),
            'CheckCompliance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCompliance,
                    request_deserializer=clausia__pb2.ExtractRequest.FromString,
                    response_serializer=clausia__pb2.CheckComplianceResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=clausia__pb2.ChatRequest.FromString,
                    response_serializer=clausia__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clausia.ClausIA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clausia.ClausIA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClausIA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/Extract',
            clausia__pb2.ExtractRequest.SerializeToString,
            clausia__pb2.ExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/ExtractMetadata',
            clausia__pb2.ExtractRequest.SerializeToString,
            clausia__pb2.ExtractMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/Summarize',
            clausia__pb2.SummarizeRequest.SerializeToString,
            clausia__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/AnalyzeRisk',
            clausia__pb2.ExtractRequest.SerializeToString,
            clausia__pb2.AnalyzeRiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCompliance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/CheckCompliance',
            clausia__pb2.ExtractRequest.SerializeToString,
            clausia__pb2.CheckComplianceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clausia.ClausIA/Chat',
            clausia__pb2.ChatRequest.SerializeToString,
            clausia__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
